spring:
  datasource:
    url: jdbc:sqlserver://10.20.30.196:1433;encrypt=false;database=hncb;
    username: sa
    password: 1qaz2wsx#EDC
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
